### ISSUE TITLE
3.14.36-FC.01 and 3.18.9-FC.01 device-mapper error.

### ISSUE THREAD

**Issue by dziq** [fearedbliss/bliss-overlay#4] opened 2015-03-23 08:31 UTC
Hi, I've just upgrade your bliss-kernel to newest one 3.14.36-FC.01 and there is an error. When I enter password for my encrypted device I see something like this:
device-mapper: reload ioctl on vault_0 failed: Invalid argument
device-mapper: reload ioctl on vault_0 failed: Invalid argument
And then once again:
[*] Enter passphrase:
and so on...

The issue also apper in masked 3.18.9-FC.01 version. Everything is ok with 3.14.35-KS.01.

**Comment by fearedbliss** [comment] 2015-03-23 12:34
Hey Bartosz,

Starting with 3.14.36, I'm not using my original kernel config anymore, but
the fedora kernel config. That error night have to do with fedora not
compiling device-mapper into the kernel but having it as a module. I'll
probably make it built it but try remaking the initramfs with the device
mapper module and any other encryption related modules and let me know what
happens.

**Comment by dziq** [comment] 2015-03-23 13:19
Jonathan,
I don't know what module to add into initramfs Addon.py. I've added dm-crypt but at start I have no module find dm-crypt.

**Comment by fearedbliss** [comment] 2015-03-23 13:20
Did you remake the initramfs after adding it into the bliss initramfs
addons.py?

**Comment by dziq** [comment] 2015-03-23 13:22
Yes
bliss-initramfs 4 3.18.9-FC.01 -> encrypted normal for 3.18.9 kernel

**Comment by fearedbliss** [comment] 2015-03-23 13:23
Does that option ask you for a kernel modules path after you add the module
into the list?

**Comment by dziq** [comment] 2015-03-23 13:25
No.

**Comment by fearedbliss** [comment] 2015-03-23 13:27
That's probably why lol. It might be a bug or something else is going on.
I'll need to check.

**Comment by fearedbliss** [comment] 2015-03-23 13:27
What version are you running?

**Comment by dziq** [comment] 2015-03-23 13:28
Should I add somethig to bliss-boot?
sys-kernel/bliss-initramfs-6.1.3

**Comment by fearedbliss** [comment] 2015-03-23 13:29
No. Bliss boot shouldn't know about this.

**Comment by dziq** [comment] 2015-03-23 13:31
Ok, when I eselect kernel set to 3.18.9 bliss-initramfs asks me about my running kernel or other I've entered 3.18.9-FC.01
But still the same error about not found module

**Comment by fearedbliss** [comment] 2015-03-23 13:32
Oh wait, you are getting the error when you are creating the initramfs?

**Comment by dziq** [comment] 2015-03-23 13:33
No. During boot.

**Comment by fearedbliss** [comment] 2015-03-23 14:11
Alright. I will take a look

**Comment by fearedbliss** [comment] 2015-03-23 15:37
From some preliminary checking, it seems that the modules aren't being
copied into the initramfs when we use the 'addon.py' file, this is a
regression. I'll check what's going on later tonight and release a fix.

I want to avoid diverging to much from the Fedora configuration, but if
needed, I will make more stuff built in and release a new kernel.

On Mon, Mar 23, 2015 at 10:11 AM, Jonathan Vasquez <jvasquez1011@gmail.com>
wrote:

> Alright. I will take a look
> On Mar 23, 2015 9:33 AM, "Bartosz Nitkiewicz" <notifications@github.com>
> wrote:
>
>> No. During boot.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fearedbliss/bliss-overlay/issues/4#issuecomment-84998598>
>> .
>>
>


-- 
Jonathan Vasquez

**Comment by fearedbliss** [comment] 2015-03-24 04:45
Hey Bartosz,

I found the problem and fixed it in version 6.1.4. Pushed to my ebuild as
stable.

https://github.com/fearedbliss/bliss-overlay/tree/master/sys-kernel/bliss-initramfs

also I tested gentoo / on encrypted btrfs on my laptop
 with my 3.18.9 bliss-kernel and just adding 'dm-crypt' in the Addon.py
worked :).

Please test and let me know.

- Jonathan

On Mon, Mar 23, 2015 at 11:37 AM, Jonathan Vasquez <jvasquez1011@gmail.com>
wrote:

> From some preliminary checking, it seems that the modules aren't being
> copied into the initramfs when we use the 'addon.py' file, this is a
> regression. I'll check what's going on later tonight and release a fix.
>
> I want to avoid diverging to much from the Fedora configuration, but if
> needed, I will make more stuff built in and release a new kernel.
>
> On Mon, Mar 23, 2015 at 10:11 AM, Jonathan Vasquez <jvasquez1011@gmail.com
> > wrote:
>
>> Alright. I will take a look
>> On Mar 23, 2015 9:33 AM, "Bartosz Nitkiewicz" <notifications@github.com>
>> wrote:
>>
>>> No. During boot.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/fearedbliss/bliss-overlay/issues/4#issuecomment-84998598>
>>> .
>>>
>>
>
>
> --
> Jonathan Vasquez
>
>


-- 
Jonathan Vasquez

**Comment by dziq** [comment] 2015-03-24 07:50
Works perfect!!! Thanks Jonathan.

**Comment by fearedbliss** [comment] 2015-03-24 12:30
Awesome! Glad to have helped.

**Comment by fearedbliss** [comment] 2015-03-27 15:11
Hey Bartosz,

I'm going to keep my philosophy of that boot critical modules should be
built into the kernel, so for all new kernels, the btrfs and dm-crypt
modules will be built in. For other lesser known hdd drivers or other fs
like (reiserfs, jfs, xfs) I won't be building this in now. If people need
these, they will need to include modules for those. ext4/btrfs are the only
fs drivers that are built in.

I'll be releasing the new kernels in a bit: 3.14.37, 3.18.10 (-r1 that
includes dm-crypt as built in), and 3.19.3.

I almost forgot to mention, I've also decided to make the raid0, raid1 (and
raid10), and raid456
 modules built into the kernel as well since this falls under critical boot
related files.

- Jonathan

On Tue, Mar 24, 2015 at 8:30 AM, Jonathan Vasquez <jvasquez1011@gmail.com>
wrote:

> Awesome! Glad to have helped.
> On Mar 24, 2015 3:50 AM, "Bartosz Nitkiewicz" <notifications@github.com>
> wrote:
>
>> Works perfect!!! Thanks Jonathan.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fearedbliss/bliss-overlay/issues/4#issuecomment-85383272>
>> .
>>
>


-- 
Jonathan Vasquez

**Comment by dziq** [comment] 2015-03-27 19:50
Thank you so much. I will test it and let you know.

2015-03-27 16:11 GMT+01:00 Jonathan Vasquez <notifications@github.com>:

> Hey Bartosz,
>
> I'm going to keep my philosophy of that boot critical modules should be
> built into the kernel, so for all new kernels, the btrfs and dm-crypt
> modules will be built in. For other lesser known hdd drivers or other fs
> like (reiserfs, jfs, xfs) I won't be building this in now. If people need
> these, they will need to include modules for those. ext4/btrfs are the only
> fs drivers that are built in.
>
> I'll be releasing the new kernels in a bit: 3.14.37, 3.18.10 (-r1 that
> includes dm-crypt as built in), and 3.19.3.
>
> I almost forgot to mention, I've also decided to make the raid0, raid1 (and
> raid10), and raid456
> modules built into the kernel as well since this falls under critical boot
> related files.
>
> - Jonathan
>
> On Tue, Mar 24, 2015 at 8:30 AM, Jonathan Vasquez <jvasquez1011@gmail.com>
> wrote:
>
> > Awesome! Glad to have helped.
> > On Mar 24, 2015 3:50 AM, "Bartosz Nitkiewicz" <notifications@github.com>
> > wrote:
> >
> >> Works perfect!!! Thanks Jonathan.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/fearedbliss/bliss-overlay/issues/4#issuecomment-85383272
> >
> >> .
> >>
> >
>
>
> --
> Jonathan Vasquez
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fearedbliss/bliss-overlay/issues/4#issuecomment-86968721>
> .
>



-- 
Bartosz Nitkiewicz

**Comment by dziq** [comment] 2015-03-27 20:03
3.19.3 works like it should. Thanks

2015-03-27 20:49 GMT+01:00 Bartosz Nitkiewicz <bartosz@nitkiewicz.eu>:

> Thank you so much. I will test it and let you know.
>
> 2015-03-27 16:11 GMT+01:00 Jonathan Vasquez <notifications@github.com>:
>
>> Hey Bartosz,
>>
>> I'm going to keep my philosophy of that boot critical modules should be
>> built into the kernel, so for all new kernels, the btrfs and dm-crypt
>> modules will be built in. For other lesser known hdd drivers or other fs
>> like (reiserfs, jfs, xfs) I won't be building this in now. If people need
>> these, they will need to include modules for those. ext4/btrfs are the
>> only
>> fs drivers that are built in.
>>
>> I'll be releasing the new kernels in a bit: 3.14.37, 3.18.10 (-r1 that
>> includes dm-crypt as built in), and 3.19.3.
>>
>> I almost forgot to mention, I've also decided to make the raid0, raid1
>> (and
>> raid10), and raid456
>> modules built into the kernel as well since this falls under critical boot
>> related files.
>>
>> - Jonathan
>>
>> On Tue, Mar 24, 2015 at 8:30 AM, Jonathan Vasquez <jvasquez1011@gmail.com
>> >
>> wrote:
>>
>> > Awesome! Glad to have helped.
>> > On Mar 24, 2015 3:50 AM, "Bartosz Nitkiewicz" <notifications@github.com
>> >
>> > wrote:
>> >
>> >> Works perfect!!! Thanks Jonathan.
>> >>
>> >> —
>> >> Reply to this email directly or view it on GitHub
>> >> <
>> https://github.com/fearedbliss/bliss-overlay/issues/4#issuecomment-85383272
>> >
>> >> .
>> >>
>> >
>>
>>
>> --
>> Jonathan Vasquez
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fearedbliss/bliss-overlay/issues/4#issuecomment-86968721>
>> .
>>
>
>
>
> --
> Bartosz Nitkiewicz
>



-- 
Bartosz Nitkiewicz

**Comment by fearedbliss** [comment] 2015-03-27 20:52
Awesome. Closing.

**Closed by fearedbliss** 2015-03-27 20:52 UTC
